services:
  web:
    build: .
    ports:
      - "5050:5000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=counter_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: counter_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
